name: Deployment
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v5

      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Lint project
        run: npm run lint

      - name: Test project
        run: npm run test

      - name: Build project
        run: npm run build

     